name: Bug Report
description: File a bug report to help us improve the project.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: '## :beetle: Bug Report :beetle:'
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Please provide a clear and concise description of the bug.'
      placeholder: |
        When I click the '...' button, the page refreshes instead of showing a confirmation message.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 'Steps to Reproduce the Bug'
      description: 'Provide the steps to reproduce the bug, be specific.'
      placeholder: |
        1. Go to the '...' page.
        2. Click on the '...' button.
        3. Scroll down to '...'.
        4. Observe the error.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected Behavior'
      description: 'Please describe the expected behavior when the steps above are followed.'
      placeholder: |
        After clicking the '...' button, a confirmation message should appear.
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: 'Actual Behavior'
      description: 'Please describe the actual behavior that you experienced when following the steps above.'
      placeholder: 'The page refreshes without showing a confirmation message.'
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional Context / Screenshots'
      description: 'Provide any additional context or information that may help diagnose the issue.'
      placeholder: 'The issue occurs in Chrome 96.0.4664.93 on macOS 11.6.1.'
    validations:
      required: false
 